In [47]:
import pandas as pd

In [48]:
df = pd.read_csv('salario_prof.csv')
df

    UF   Salario        Regiao
0   MS  13007.12  Centro-Oeste
1   MA   8452.03      Nordeste
2   PA   8289.86         Norte
3   RR   7700.47         Norte
4   MT   7343.44  Centro-Oeste
5   PB   6944.09      Nordeste
6   RN   6814.88      Nordeste
7   AP   6600.98         Norte
8   DF   6427.71  Centro-Oeste
9   SE   6176.76      Nordeste
10  TO   6130.70         Norte
11  PE   5841.91      Nordeste
12  AL   5767.15      Nordeste
13  ES   5685.97       Sudeste
14  AM   5631.18         Norte
15  SP   5565.00       Sudeste
16  AC   5370.35         Norte
17  GO   5160.49  Centro-Oeste
18  RO   5118.41         Norte
19  RS   5111.05           Sul
20  SC   5026.80           Sul
21  PI   4984.17      Nordeste
22  BA   4965.24      Nordeste
23  CE   4961.73      Nordeste
24  PR   4920.55           Sul
25  MG   4867.97       Sudeste

In [49]:
df.dtypes

UF          object
Salario    float64
Regiao      object
dtype: object

In [50]:
list(df.columns)

['UF', 'Salario', 'Regiao']

In [54]:
#O estado com menor salário
menor_salario = df.loc[df['Salario']==df['Salario'].min()] #trazendo o menor salário
print("O estado com menor salário é: ")
menor_salario

O estado com menor salário é:

    UF  Salario   Regiao
25  MG  4867.97  Sudeste

In [55]:
#O estado com maior salário
menor_salario = df.loc[df['Salario']==df['Salario'].max()] #trazendo o menor salário
print("O estado com maior salário é: ")
menor_salario

O estado com maior salário é:

   UF   Salario        Regiao
0  MS  13007.12  Centro-Oeste

In [56]:
#Posição em que o estado de Goiás está
# Criando ranking
df['ranking'] = df['Salario'].rank(ascending=False, method='min')

# Pegando o ranking de Goiás
posicao = df.loc[df['UF'] == 'GO', 'ranking'].values[0]

# Print correto
print(f"O estado de Goiás ocupa a {int(posicao)}º posição no ranking de salários")

# Exibindo os dados de GO
df[df['UF'] == 'GO']

O estado de Goiás ocupa a 18º posição no ranking de salários

    UF  Salario        Regiao  ranking
17  GO  5160.49  Centro-Oeste     18.0

In [58]:
#A média salárial entre todos os estados
media = df['Salario'].sum() / df['Salario'].count()
print(f"A média salarial dos professores no Brasil é: {media:.2f}")

A média salarial dos professores no Brasil é: 6264.08

In [59]:
#Mostrar a média salárial entre todos os estados por região
media_regiao = df.groupby('Regiao')['Salario'].mean()
print("A média salarial por região brasileira:")
print(media_regiao.round(2))

A média salarial por região brasileira:
Regiao
Centro-Oeste    7984.69
Nordeste        6100.88
Norte           6405.99
Sudeste         5372.98
Sul             5019.47
Name: Salario, dtype: float64

In [60]:
#Mostrar o maior salário por região
maior_regiao = df.groupby('Regiao')['Salario'].max()

regiao_maior = maior_regiao.idxmax()
valor = maior_regiao.max()

print(f"A região com maior salário é {regiao_maior}, com R$ {valor:.2f}")

A região com maior salário é Centro-Oeste, com R$ 13007.12

In [61]:
#Mostrar o menor salário por região
menor_regiao = df.groupby('Regiao')['Salario'].min()

regiao_menor = menor_regiao.idxmin()
valor = menor_regiao.min()

print(f"A região com maior salário é {regiao_menor}, com R$ {valor:.2f}")

A região com maior salário é Sudeste, com R$ 4867.97

In [62]:
#Mostrar a média salarial por região
media_regiao = df.groupby('Regiao')['Salario'].mean()

regiao_media = media_regiao.idxmax()
valor_media = media_regiao.max()

print("Média salarial por região: ")
media_regiao.round(2)

Média salarial por região:

Regiao
Centro-Oeste    7984.69
Nordeste        6100.88
Norte           6405.99
Sudeste         5372.98
Sul             5019.47
Name: Salario, dtype: float64

In [64]:
#Mostrar a região com maior e menor média salarial
media_salarial_por_regiao = df.groupby('Regiao')['Salario'].mean().reset_index()

#encontrando regiao com a maior media
regiao_maior_media = media_salarial_por_regiao.loc[media_salarial_por_regiao['Salario'].idxmax()]

#encontrando regiao com a maior media
regiao_menor_media = media_salarial_por_regiao.loc[media_salarial_por_regiao['Salario'].idxmin()]

#exibir os resultados
print(f"A região com a maior média é: {regiao_maior_media['Regiao']} com um salário médio de R$ {regiao_maior_media['Salario']:.2f}")
print(f"A região com a menor média é: {regiao_menor_media['Regiao']} com um salário médio de R$ {regiao_menor_media['Salario']:.2f}")

A região com a maior média é: Centro-Oeste com um salário médio de R$ 7984.69
A região com a menor média é: Sul com um salário médio de R$ 5019.47